#MRO A BAD PRACTICE PROBABLY BAD CODE BECAUSE IT'S CONFUSING.

class A:
    num = 10

class B(A):
    pass

class C (A):
    num = 1

class D(B,C):
    pass

#D INHERITANCE FROM B AND C.
#C INHERITANCE FROM A THAT NUM = 10 BUT C REDIFINES NUM = 1
#B INHETICANCE FROM A BUT HAS NO VALUE
#A IS THE PARENT WITH NUM = 10

print(D.num)
print(D.mro()) #CHECKS THE ORDER THAT WILL GONNA BE USED. GOOD FOR DEBUGGIN.